import { Platform } from "react-native";

export const auraColors = {
  backgroundDeep: "#09000B",
  backgroundDark: "#190019",
  surface: "rgba(43,18,76,0.46)",
  surfaceElevated: "rgba(82,43,91,0.28)",
  surfaceBase: "rgba(43,18,76,0.46)",
  surfaceRaised: "rgba(43,18,76,0.55)",
  surfaceInteractive: "rgba(82,43,91,0.28)",
  accentMauve: "#854F6C",
  accentRose: "#DFB6B2",
  boardLight: "#F7F1EA",
  textPrimary: "#FBE4D8",
  textSecondary: "rgba(251,228,216,0.68)",
  textMuted: "rgba(251,228,216,0.48)",
  textOnLight: "#190019",
  textOnLightSecondary: "rgba(25,0,25,0.68)",
  borderDark: "rgba(251,228,216,0.10)",
  borderWarm: "rgba(223,182,178,0.18)",
} as const;

const tintColor = auraColors.accentRose;

const auraSpacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 32,
} as const;

const auraTypography = {
  screenTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900" as const,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "900" as const,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900" as const,
  },
  caption: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700" as const,
  },
  bodySecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
  },
  chipLabel: {
    fontSize: 12.5,
    lineHeight: 16,
    fontWeight: "800" as const,
  },
  buttonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900" as const,
  },
  button: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900" as const,
  },
  eyebrow: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 2.4,
    fontWeight: "700" as const,
  },
  body: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500" as const,
  },
  subtitle: {
    fontSize: 17,
    lineHeight: 26,
    fontWeight: "500" as const,
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "700" as const,
  },
  hero: {
    fontSize: 46,
    lineHeight: 52,
    fontWeight: "700" as const,
  },
  wordmark: {
    fontSize: 28,
    letterSpacing: 11,
    fontWeight: "500" as const,
  },
} as const;

const auraTokens = {
  colors: {
    background: auraColors.backgroundDeep,
    surface: auraColors.surface,
    surfaceBase: auraColors.surfaceBase,
    surfaceRaised: auraColors.surfaceRaised,
    surfaceInteractive: auraColors.surfaceInteractive,
    surfaceSoft: "rgba(82,43,91,0.22)",
    surfaceElevated: auraColors.surfaceElevated,
    glass: auraColors.surfaceBase,
    surfaceGlass: auraColors.surfaceBase,
    surface1: auraColors.surfaceBase,
    surface2: "rgba(82,43,91,0.24)",
    surface3: "rgba(82,43,91,0.32)",
    surfaceWarm: auraColors.surface,
    warmGlow: "rgba(223,182,178,0.04)",
    textPrimary: auraColors.textPrimary,
    textSecondary: auraColors.textSecondary,
    textMuted: auraColors.textMuted,
    primary: auraColors.accentRose,
    primaryText: auraColors.textOnLight,
    primaryPurple: auraColors.accentMauve,
    softPurple: auraColors.accentRose,
    lightPurple: auraColors.accentRose,
    ctaCream: auraColors.accentRose,
    outfitBoardBackground: auraColors.boardLight,
    border: auraColors.borderDark,
    borderStrong: "rgba(251,228,216,0.14)",
    purpleBorder: "rgba(223,182,178,0.22)",
    purpleGlow: "rgba(223,182,178,0.05)",
    purpleSurface: "rgba(223,182,178,0.12)",
    purpleSurfaceStrong: "rgba(223,182,178,0.18)",
    chipBackground: "rgba(43,18,76,0.44)",
    inputBackground: "rgba(43,18,76,0.50)",
    dockBackground: "rgba(9,0,11,0.82)",
    danger: "#FF4D4F",
    dangerSurface: "rgba(255,77,79,0.12)",
    dangerBorder: "rgba(255,77,79,0.28)",
    success: "#22C55E",
    warning: "#F59E0B",
    auraPink: auraColors.accentRose,
    auraChampagne: auraColors.boardLight,
    auraBlue: auraColors.accentMauve,
    auraLavender: auraColors.accentRose,
    iridescentStart: auraColors.accentMauve,
    iridescentMid: auraColors.accentRose,
    iridescentEnd: auraColors.boardLight,
    borderSoft: "rgba(251,228,216,0.08)",
  },
  gradients: {
    aura: [auraColors.accentMauve, auraColors.accentRose, auraColors.boardLight, auraColors.accentRose] as const,
    background: ["#120014", auraColors.backgroundDeep, auraColors.backgroundDark] as const,
  },
  shadows: {
    auraGlow: "rgba(223,182,178,0.14)",
  },
  radii: {
    small: 12,
    medium: 18,
    large: 24,
    xl: 28,
    card: 28,
    pill: 999,
    button: 999,
  },
  spacing: auraSpacing,
  typography: auraTypography,
} as const;

function buildPalette() {
  return {
    backgroundDeep: auraColors.backgroundDeep,
    backgroundDark: auraColors.backgroundDark,
    background: auraTokens.colors.background,
    surface: auraTokens.colors.surface,
    surfaceBase: auraTokens.colors.surfaceBase,
    surfaceRaised: auraTokens.colors.surfaceRaised,
    surfaceInteractive: auraTokens.colors.surfaceInteractive,
    surfaceSoft: auraTokens.colors.surfaceSoft,
    surfaceElevated: auraTokens.colors.surfaceElevated,
    glass: auraTokens.colors.glass,
    surfaceGlass: auraTokens.colors.surfaceGlass,
    card: auraTokens.colors.surface,
    input: auraTokens.colors.inputBackground,
    inputBackground: auraTokens.colors.inputBackground,
    chipBackground: auraTokens.colors.chipBackground,
    surface1: auraTokens.colors.surface1,
    surface2: auraTokens.colors.surface2,
    surface3: auraTokens.colors.surface3,
    surfaceWarm: auraTokens.colors.surfaceWarm,
    warmGlow: auraTokens.colors.warmGlow,
    text: auraTokens.colors.textPrimary,
    textPrimary: auraTokens.colors.textPrimary,
    textSecondary: auraTokens.colors.textSecondary,
    textMuted: auraTokens.colors.textMuted,
    primary: auraTokens.colors.primary,
    primaryText: auraTokens.colors.primaryText,
    textOnLight: auraColors.textOnLight,
    textOnLightSecondary: auraColors.textOnLightSecondary,
    border: auraTokens.colors.border,
    borderDark: auraColors.borderDark,
    borderWarm: auraColors.borderWarm,
    borderStrong: auraTokens.colors.borderStrong,
    borderSoft: auraTokens.colors.borderSoft,
    purpleBorder: auraTokens.colors.purpleBorder,
    purpleGlow: auraTokens.colors.purpleGlow,
    purpleSurface: auraTokens.colors.purpleSurface,
    purpleSurfaceStrong: auraTokens.colors.purpleSurfaceStrong,
    tint: tintColor,
    accent: auraTokens.colors.ctaCream,
    accentMauve: auraColors.accentMauve,
    accentRose: auraColors.accentRose,
    accentSoft: auraTokens.colors.purpleSurface,
    primaryPurple: auraTokens.colors.primaryPurple,
    softPurple: auraTokens.colors.softPurple,
    lightPurple: auraTokens.colors.lightPurple,
    ctaCream: auraTokens.colors.ctaCream,
    ctaText: auraColors.textOnLight,
    primaryCta: auraColors.accentRose,
    primaryCtaText: auraColors.textOnLight,
    secondaryCta: "rgba(43,18,76,0.52)",
    secondaryCtaText: auraColors.textPrimary,
    outfitBoardBackground: auraTokens.colors.outfitBoardBackground,
    boardLight: auraColors.boardLight,
    auraPink: auraTokens.colors.auraPink,
    auraChampagne: auraTokens.colors.auraChampagne,
    auraBlue: auraTokens.colors.auraBlue,
    auraLavender: auraTokens.colors.auraLavender,
    iridescentStart: auraTokens.colors.iridescentStart,
    iridescentMid: auraTokens.colors.iridescentMid,
    iridescentEnd: auraTokens.colors.iridescentEnd,
    success: auraTokens.colors.success,
    warning: auraTokens.colors.warning,
    danger: auraTokens.colors.danger,
    dangerSurface: auraTokens.colors.dangerSurface,
    dangerBorder: auraTokens.colors.dangerBorder,
    muted: auraTokens.colors.surfaceElevated,
    shadow: "rgba(0,0,0,0.52)",
    overlay: "rgba(9,0,11,0.72)",
    glassBorder: auraTokens.colors.border,
    glassInnerBorder: "rgba(251,228,216,0.05)",
    glassEdge: "rgba(251,228,216,0.08)",
    lens: auraTokens.colors.purpleSurfaceStrong,
    lensInner: "rgba(251,228,216,0.05)",
    scrimTop: "rgba(9,0,11,0)",
    scrimMid: "rgba(9,0,11,0.30)",
    scrimBottom: "rgba(9,0,11,0.70)",
    dockBackground: auraTokens.colors.dockBackground,
    dockIcon: "rgba(251,228,216,0.58)",
    aiAccent: auraColors.accentRose,
    icon: auraTokens.colors.textSecondary,
    tabIconDefault: "rgba(251,228,216,0.58)",
    tabIconSelected: auraColors.textPrimary,
  };
}

export const ThemeTokens = {
  light: auraTokens,
  dark: auraTokens,
} as const;

export const Colors = {
  light: buildPalette(),
  dark: buildPalette(),
} as const;

export type AppColors = typeof Colors.dark;
export type AppThemeTokens = typeof ThemeTokens.dark;

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
