import { Platform } from "react-native";

export const auraColors = {
  backgroundDeep: "#080709",
  backgroundDark: "#111014",
  surface: "rgba(24,22,30,0.72)",
  surfaceElevated: "rgba(34,31,40,0.82)",
  surfaceBase: "rgba(24,22,30,0.72)",
  surfaceRaised: "rgba(34,31,40,0.86)",
  surfaceInteractive: "rgba(42,36,50,0.66)",
  accentMauve: "#854F6C",
  accentRose: "#DFB6B2",
  boardLight: "#F7F1EA",
  textPrimary: "#FBE4D8",
  textSecondary: "rgba(251,228,216,0.82)",
  textMuted: "rgba(251,228,216,0.64)",
  textOnLight: "#111014",
  textOnLightSecondary: "rgba(17,16,20,0.68)",
  borderDark: "rgba(251,228,216,0.10)",
  borderWarm: "rgba(223,182,178,0.18)",
} as const;

const tintColor = auraColors.accentRose;

const auraSpacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
} as const;

const auraTypography = {
  screenTitle: {
    fontSize: 28,
    lineHeight: 35,
    fontWeight: "700" as const,
    letterSpacing: -0.35,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  section: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600" as const,
    letterSpacing: -0.15,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "600" as const,
    letterSpacing: -0.15,
  },
  heading: {
    fontSize: 24,
    lineHeight: 31,
    fontWeight: "600" as const,
    letterSpacing: -0.3,
  },
  caption: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500" as const,
  },
  metadata: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500" as const,
    letterSpacing: 1.4,
  },
  bodySecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
  },
  bodyStrong: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600" as const,
  },
  chipLabel: {
    fontSize: 12.5,
    lineHeight: 16,
    fontWeight: "500" as const,
  },
  buttonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600" as const,
    letterSpacing: 0.1,
  },
  button: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600" as const,
    letterSpacing: 0.1,
  },
  eyebrow: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 2.4,
    fontWeight: "600" as const,
  },
  body: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "400" as const,
  },
  subtitle: {
    fontSize: 17,
    lineHeight: 26,
    fontWeight: "500" as const,
  },
  title: {
    fontSize: 34,
    lineHeight: 41,
    fontWeight: "700" as const,
    letterSpacing: -0.45,
  },
  hero: {
    fontSize: 46,
    lineHeight: 53,
    fontWeight: "700" as const,
    letterSpacing: -0.55,
  },
  wordmark: {
    fontSize: 28,
    letterSpacing: 11,
    fontWeight: "500" as const,
  },
} as const;

const auraTokens = {
  colors: {
    background: auraColors.backgroundDeep,
    surface: auraColors.surface,
    surfaceBase: auraColors.surfaceBase,
    surfaceRaised: auraColors.surfaceRaised,
    surfaceInteractive: auraColors.surfaceInteractive,
    surfaceSoft: "rgba(42,36,50,0.54)",
    surfaceMuted: "rgba(34,31,40,0.64)",
    surfaceElevated: auraColors.surfaceElevated,
    glass: "rgba(16,15,20,0.68)",
    surfaceGlass: "rgba(18,17,22,0.70)",
    surface1: auraColors.surfaceBase,
    surface2: "rgba(34,31,40,0.70)",
    surface3: "rgba(42,36,50,0.76)",
    surfaceWarm: auraColors.surface,
    warmGlow: "rgba(223,182,178,0.04)",
    textPrimary: auraColors.textPrimary,
    textSecondary: auraColors.textSecondary,
    textMuted: auraColors.textMuted,
    primary: auraColors.accentRose,
    accent: auraColors.accentRose,
    accentSoft: "rgba(223,182,178,0.12)",
    primaryText: auraColors.textOnLight,
    primaryPurple: auraColors.accentMauve,
    softPurple: auraColors.accentRose,
    lightPurple: auraColors.accentRose,
    ctaCream: auraColors.accentRose,
    outfitBoardBackground: auraColors.boardLight,
    border: auraColors.borderDark,
    borderStrong: "rgba(251,228,216,0.14)",
    purpleBorder: "rgba(223,182,178,0.22)",
    purpleGlow: "rgba(223,182,178,0.05)",
    purpleSurface: "rgba(223,182,178,0.10)",
    purpleSurfaceStrong: "rgba(223,182,178,0.15)",
    chipBackground: "rgba(34,31,40,0.70)",
    inputBackground: "rgba(18,17,22,0.78)",
    dockBackground: "rgba(8,7,9,0.84)",
    dockScrimTop: "rgba(9,0,11,0)",
    dockScrimMid: "rgba(9,0,11,0.03)",
    dockScrimBottom: "rgba(9,0,11,0.08)",
    danger: "#FF4D4F",
    destructive: "#FF4D4F",
    dangerSurface: "rgba(255,77,79,0.12)",
    dangerBorder: "rgba(255,77,79,0.28)",
    success: "#22C55E",
    warning: "#F59E0B",
    auraPink: auraColors.accentRose,
    auraChampagne: auraColors.boardLight,
    auraBlue: auraColors.accentMauve,
    auraLavender: auraColors.accentRose,
    iridescentStart: auraColors.accentMauve,
    iridescentMid: auraColors.accentRose,
    iridescentEnd: auraColors.boardLight,
    borderSoft: "rgba(251,228,216,0.07)",
  },
  gradients: {
    aura: [auraColors.accentMauve, auraColors.accentRose, auraColors.boardLight, auraColors.accentRose] as const,
    background: ["#111014", auraColors.backgroundDeep, auraColors.backgroundDark] as const,
  },
  shadows: {
    auraGlow: "rgba(223,182,178,0.14)",
    subtle: {
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 2,
    },
    elevated: {
      shadowColor: "#000",
      shadowOpacity: 0.16,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 16 },
      elevation: 6,
    },
  },
  radii: {
    sm: 12,
    md: 18,
    lg: 24,
    small: 12,
    medium: 18,
    large: 24,
    xl: 28,
    xxl: 32,
    card: 28,
    full: 999,
    pill: 999,
    button: 999,
  },
  motion: {
    fast: 120,
    normal: 180,
    slow: 280,
    pressScale: 0.97,
  },
  spacing: auraSpacing,
  typography: auraTypography,
} as const;

function buildPalette() {
  return {
    backgroundDeep: auraColors.backgroundDeep,
    backgroundDark: auraColors.backgroundDark,
    background: auraTokens.colors.background,
    surface: auraTokens.colors.surface,
    surfaceBase: auraTokens.colors.surfaceBase,
    surfaceRaised: auraTokens.colors.surfaceRaised,
    surfaceInteractive: auraTokens.colors.surfaceInteractive,
    surfaceSoft: auraTokens.colors.surfaceSoft,
    surfaceMuted: auraTokens.colors.surfaceMuted,
    surfaceElevated: auraTokens.colors.surfaceElevated,
    glass: auraTokens.colors.glass,
    surfaceGlass: auraTokens.colors.surfaceGlass,
    card: auraTokens.colors.surface,
    input: auraTokens.colors.inputBackground,
    inputBackground: auraTokens.colors.inputBackground,
    chipBackground: auraTokens.colors.chipBackground,
    surface1: auraTokens.colors.surface1,
    surface2: auraTokens.colors.surface2,
    surface3: auraTokens.colors.surface3,
    surfaceWarm: auraTokens.colors.surfaceWarm,
    warmGlow: auraTokens.colors.warmGlow,
    text: auraTokens.colors.textPrimary,
    textPrimary: auraTokens.colors.textPrimary,
    textSecondary: auraTokens.colors.textSecondary,
    textMuted: auraTokens.colors.textMuted,
    primary: auraTokens.colors.primary,
    primaryText: auraTokens.colors.primaryText,
    textOnLight: auraColors.textOnLight,
    textOnLightSecondary: auraColors.textOnLightSecondary,
    border: auraTokens.colors.border,
    borderDark: auraColors.borderDark,
    borderWarm: auraColors.borderWarm,
    borderStrong: auraTokens.colors.borderStrong,
    borderSoft: auraTokens.colors.borderSoft,
    purpleBorder: auraTokens.colors.purpleBorder,
    purpleGlow: auraTokens.colors.purpleGlow,
    purpleSurface: auraTokens.colors.purpleSurface,
    purpleSurfaceStrong: auraTokens.colors.purpleSurfaceStrong,
    tint: tintColor,
    accent: auraTokens.colors.accent,
    accentMauve: auraColors.accentMauve,
    accentRose: auraColors.accentRose,
    accentSoft: auraTokens.colors.accentSoft,
    primaryPurple: auraTokens.colors.primaryPurple,
    softPurple: auraTokens.colors.softPurple,
    lightPurple: auraTokens.colors.lightPurple,
    ctaCream: auraTokens.colors.ctaCream,
    ctaText: auraColors.textOnLight,
    primaryCta: auraColors.accentRose,
    primaryCtaText: auraColors.textOnLight,
    secondaryCta: "rgba(34,31,40,0.72)",
    secondaryCtaText: auraColors.textPrimary,
    outfitBoardBackground: auraTokens.colors.outfitBoardBackground,
    boardLight: auraColors.boardLight,
    auraPink: auraTokens.colors.auraPink,
    auraChampagne: auraTokens.colors.auraChampagne,
    auraBlue: auraTokens.colors.auraBlue,
    auraLavender: auraTokens.colors.auraLavender,
    iridescentStart: auraTokens.colors.iridescentStart,
    iridescentMid: auraTokens.colors.iridescentMid,
    iridescentEnd: auraTokens.colors.iridescentEnd,
    success: auraTokens.colors.success,
    warning: auraTokens.colors.warning,
    danger: auraTokens.colors.danger,
    destructive: auraTokens.colors.destructive,
    dangerSurface: auraTokens.colors.dangerSurface,
    dangerBorder: auraTokens.colors.dangerBorder,
    muted: auraTokens.colors.surfaceElevated,
    shadow: "rgba(0,0,0,0.52)",
    overlay: "rgba(9,0,11,0.72)",
    glassBorder: auraTokens.colors.border,
    glassInnerBorder: "rgba(251,228,216,0.05)",
    glassEdge: "rgba(251,228,216,0.08)",
    lens: auraTokens.colors.purpleSurfaceStrong,
    lensInner: "rgba(251,228,216,0.05)",
    scrimTop: "rgba(9,0,11,0)",
    scrimMid: "rgba(9,0,11,0.30)",
    scrimBottom: "rgba(9,0,11,0.70)",
    dockBackground: auraTokens.colors.dockBackground,
    dockScrimTop: auraTokens.colors.dockScrimTop,
    dockScrimMid: auraTokens.colors.dockScrimMid,
    dockScrimBottom: auraTokens.colors.dockScrimBottom,
    dockIcon: "rgba(251,228,216,0.72)",
    aiAccent: auraColors.accentRose,
    icon: auraTokens.colors.textSecondary,
    tabIconDefault: "rgba(251,228,216,0.72)",
    tabIconSelected: auraColors.textPrimary,
  };
}

export const ThemeTokens = {
  light: auraTokens,
  dark: auraTokens,
} as const;

export const Colors = {
  light: buildPalette(),
  dark: buildPalette(),
} as const;

export type AppColors = typeof Colors.dark;
export type AppThemeTokens = typeof ThemeTokens.dark;

export const Fonts = Platform.select({
  ios: {
    sans: undefined,
    serif: undefined,
    rounded: undefined,
    mono: "Menlo",
  },
  android: {
    sans: "sans-serif",
    serif: "serif",
    rounded: "sans-serif",
    mono: "monospace",
  },
  default: {
    sans: "sans-serif",
    serif: "serif",
    rounded: "sans-serif",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
